### ISSUE TITLE
Does not load front page

### ISSUE THREAD

**Issue by martinellison** [radek00/http-server#30]
If I run this server in a directory with an `index.html` , it should display the rendered  `index.html` page, but I just get a directory listing.

Also, 'simple' has a 'p' in it.

**Comment by radek00** [comment]
Currently there's no implementation for rendering custom html pages. It always returns the default one and lists the directory, but I could work on adding such functionality.

**Comment by radek00** [comment]
You could use it as a crate and register your own endpoints that would return the html that you want, but there's currently no way to do that through the cli app.

**Comment by radek00** [comment]
Ability to serve custom html files is now added. You can use it with the --index option.
